# Server
server.port=8085

# PostgreSQL Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/natpac_travel_db
spring.datasource.username=postgres
spring.datasource.password=280304

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
